version: "3.8"

services:
  fraud-detector:
    build:
      context: .
    container_name: fraud-detection-app
    volumes:
      - ./data:/app/data
      - /home/ubuntu/.aws:/root/.aws:ro
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_DEFAULT_REGION=ap-south-1
    restart: on-failure
